
- name: download f5-* packages
  get_url: url={{ item }} dest=/tmp timeout=30
  with_items:
    - "{{ download_prefix }}/f5-sdk-{{ versions.f5sdk }}.el7.noarch.rpm"
    - "{{ download_prefix }}/f5-icontrol-rest-{{ versions.icontrol }}.el7.noarch.rpm"
    - "{{ download_prefix }}/f5-openstack-lbaasv2-driver-{{ versions.driver }}.el7.noarch.rpm"
    - "{{ download_prefix }}/f5-openstack-agent-{{ versions.agent }}.el7.noarch.rpm"

# yum uninstall is pretty slow in osp, so use rpm instead.
- name: uninstall legacy f5-* using rpm
  shell: |
    f5_rpms=`rpm -qa | grep -E "^f5-"`
    if [ -n "$f5_rpms" ]; then rpm -ev $f5_rpms; fi
  when: test_env == "osp"

- name: uninstall legacy f5-* using yum
  yum:
    name:
      - f5-openstack-agent.noarch
      - f5-openstack-lbaasv2-driver.noarch
      - f5-icontrol-rest.noarch
      - f5-sdk.noarch
    state: removed
  when: test_env != "osp"

- name: install f5-*
  shell: |
    rpm -ivh \
      f5-sdk-{{ versions.f5sdk }}.el7.noarch.rpm \
      f5-icontrol-rest-{{ versions.icontrol }}.el7.noarch.rpm \
      f5-openstack-lbaasv2-driver-{{ versions.driver }}.el7.noarch.rpm \
      f5-openstack-agent-{{ versions.agent }}.el7.noarch.rpm
  args:
    chdir: /tmp
    removes: f5-openstack-agent-{{ versions.agent }}.el7.noarch.rpm
    warn: False