---
- import_tasks: ./task-create-testcase-tenant.yml
  when: tenant_name is defined

- name: "{{ testcasename }}: create loadbalancer"
  shell: |
    source {{ openrc }} && {{ item }}
  with_items:
    - neutron --debug lbaas-loadbalancer-create --name {{ loadbalancer }} {{ loadbalancer_additional_options}} {{ subnet }}

- name: "{{ testcasename }}: create lbaasv2 resources"
  shell: |
    source {{ openrc }} && bash /tmp/scripts/wait_assert_lb_active.sh {{ loadbalancer }} && {{ item }}
  with_items:
    - neutron --debug lbaas-pool-create --name {{ pool }} --loadbalancer {{ loadbalancer }} --lb-algorithm ROUND_ROBIN --protocol {{ pool_protocol }}
    - neutron --debug lbaas-listener-create --name {{ listener }} --loadbalancer {{ loadbalancer }} --default-pool {{ pool }} --protocol {{ listener_protocol }} --protocol-port {{ listener_tcpport }} {{ listener_additional_options }}
    - neutron --debug lbaas-healthmonitor-create --name {{ healthmonitor }} --delay 15 --timeout 25 --max-retries 10 --type {{ healthmonitor_protocol }} --pool {{ pool }}

- name: "{{ testcasename }}: create members under pool {{ pool }}"
  shell: |
    source {{ openrc }} && \
      bash /tmp/scripts/wait_assert_lb_active.sh {{ loadbalancer }} && \
      neutron --debug lbaas-member-create --subnet {{ hostvars[item].subnet }} --address {{ item }} --protocol-port {{ member_tcpport }} {{ pool }}
  with_items:
    - "{{ hostvars[inventory_hostname]['groups']['pool1'] }}"

- name: "{{ testcasename }}: waiting for resource created"
  shell: |
    source {{ openrc }} && \
      bash /tmp/scripts/wait_assert_lb_active.sh {{ loadbalancer }}